/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerIndexRouteImport } from './routes/server/index'
import { Route as ServerNewRouteImport } from './routes/server/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIndexRoute = ServerIndexRouteImport.update({
  id: '/server/',
  path: '/server/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerNewRoute = ServerNewRouteImport.update({
  id: '/server/new',
  path: '/server/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/server/new': typeof ServerNewRoute
  '/server/': typeof ServerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/server/new': typeof ServerNewRoute
  '/server': typeof ServerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/server/new': typeof ServerNewRoute
  '/server/': typeof ServerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/server/new' | '/server/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/server/new' | '/server'
  id: '__root__' | '/' | '/server/new' | '/server/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServerNewRoute: typeof ServerNewRoute
  ServerIndexRoute: typeof ServerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/': {
      id: '/server/'
      path: '/server'
      fullPath: '/server/'
      preLoaderRoute: typeof ServerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/new': {
      id: '/server/new'
      path: '/server/new'
      fullPath: '/server/new'
      preLoaderRoute: typeof ServerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServerNewRoute: ServerNewRoute,
  ServerIndexRoute: ServerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
